User.create(username: "Dirty Weed", password: "password")
User.create(username: "Poisonhash", password: "password")
User.create(username: "Lil Crawfish", password: "password")
User.create(username: "agxra", password: "password")
Beat.create(title: "Lonely", user_id: 1)
Beat.create(title: "Nasty", user_id: 2)
Beat.create(title: "Hopeless", user_id: 3)
Beat.create(title: "Fast Life", user_id: 4)
Beat.create(title: "No Limit", user_id: 1)
Beat.create(title: "Don't Stop", user_id: 1)
Beat.create(title: "Can't Do It", user_id: 3)